#!/bin/bash

shopt -s nocasematch

MAJOR=0
MINOR=1
PATCH=0
while read line; do
    if [ ! -z "$line" ]; then
        case $line in
            fix)
                ((PATCH++))
                ;;
            feature)
                ((MINOR++))
                PATCH=0
                ;;
            break)
                ((MAJOR++))
                MINOR=0
                PATCH=0
                ;;
        esac
    fi
done < <(git log --reverse --pretty=format:"%(trailers:key=change-type,valueonly,only,unfold)")

mkdir -p target/universal/stage

cat <<! > target/universal/stage/version.github
echo "SPECIFICATION_VERSION=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
echo "IMPLEMENTATION_VERSION=$MAJOR.$MINOR.$PATCH+$(git rev-parse --short HEAD)" >> $GITHUB_ENV
!

chmod +x target/universal/stage/version.github